version: "3.3"

services:
  tensorflow_serving_sample:
    image: tensorflow/serving:2.2.0
    container_name: tensorflow_serving
    user: ${CURRENT_UID}
    volumes:
      - "../data/tf_models:/models"
    ports:
      - "8500:8500"
      - "8501:8501"
    networks:
      - image_labelling
    command:
      --model_config_file=/models/models.config --rest_api_timeout_in_ms=300000

networks:
  image_labelling:
    external: true
