version: "3.3"

services:
  service_uwsgi_prediction:
    image: dpp_prediction:20201110
    container_name: service_uwsgi_prediction
    user: ${CURRENT_UID}
    volumes:
      - "../service/flask:/app/code/flask"
      - "../data:/app/data"
      - "../logs/uwsgi:/var/log/uwsgi"
      - "../logs/flask:/app/logs/flask"
    ports:
      - "9002:9002"
    networks:
      - image_labelling
    command: /bin/bash -c "
      bash /app/code/flask/product_startup.sh
      "

networks:
  image_labelling:
    external: true
